import { build } from "esbuild-wasm";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, join } from "node:path";

const root = resolve(import.meta.dirname, "..");
const vendor = join(root, "vendor");
mkdirSync(vendor, { recursive: true });
const result = await build({ absWorkingDir: root, entryPoints: ["scripts/vendor-entry.js"],
  outfile: "vendor/schema-validator.js", bundle: true, format: "esm", platform: "node",
  target: "node24", minify: true, legalComments: "eof", metafile: true,
  banner: { js: '// Generated by npm run build:vendor. Licenses: THIRD_PARTY_NOTICES.txt' } });
const packages = [...new Set(Object.keys(result.metafile.inputs).flatMap(p => {
  const match = p.match(/^node_modules\/((?:@[^/]+\/)?[^/]+)\//);
  return match ? [match[1]] : [];
}))].sort();
const notices = packages.map(name => {
  const dir = join(root, "node_modules", name);
  const pkg = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
  let license;
  for (const file of ["LICENSE", "LICENSE.txt", "LICENSE.md", "license", "LICENSE-MIT"]) {
    try { license = readFileSync(join(dir, file), "utf8"); break; } catch {}
  }
  if (!license) throw Error(`Missing license for ${name}`);
  return `${name}@${pkg.version}\n${license.trim()}\n`;
});
writeFileSync(join(vendor, "THIRD_PARTY_NOTICES.txt"), notices.join("\n--------------------\n\n"));
console.log(`Bundled ${packages.length} runtime packages with their license notices.`);
