import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { spawn } from "node:child_process";
import { homedir, platform } from "node:os";
import { basename, join, resolve } from "node:path";
import { dataDirectory, initialize } from "./settings.js";
import { Fault } from "./errors.js";

export const API_BASE_URL = "http://127.0.0.1:17841/v1";
export const CODEX_PROFILE = "webgpt-api";
const CODEX_MARKER = "# Managed by webgpt-api. Do not edit this file manually.";

function tomlString(value) {
  return JSON.stringify(String(value));
}

function tomlArray(values) {
  return `[${values.map(tomlString).join(", ")}]`;
}

export function codexHome(env = process.env) {
  return resolve(env.CODEX_HOME || join(homedir(), ".codex"));
}

export function codexProfilePath(env = process.env) {
  return join(codexHome(env), `${CODEX_PROFILE}.config.toml`);
}

export function codexProfileText({ nodePath = process.execPath, projectRoot = resolve(import.meta.dirname, ".."), apiBaseUrl = API_BASE_URL } = {}) {
  const cliPath = join(projectRoot, "src", "cli.js");
  return `${CODEX_MARKER}
# Generated for the local webgpt-api gateway.
model = "auto"
model_provider = "webgpt_local"
web_search = "disabled"

[features]
hooks = false
apps = false
remote_plugin = false
multi_agent = false

[model_providers.webgpt_local]
name = "webgpt-api"
base_url = ${tomlString(apiBaseUrl)}
wire_api = "responses"
supports_websockets = false
request_max_retries = 0
stream_max_retries = 0

[model_providers.webgpt_local.auth]
command = ${tomlString(nodePath)}
args = ${tomlArray([cliPath, "key"])}
cwd = ${tomlString(projectRoot)}
refresh_interval_ms = 0
timeout_ms = 5000
`;
}

export function installCodexProfile({ env = process.env, nodePath = process.execPath, projectRoot = resolve(import.meta.dirname, ".."), apiBaseUrl = API_BASE_URL } = {}) {
  const directory = codexHome(env);
  const path = codexProfilePath(env);
  const content = codexProfileText({ nodePath, projectRoot, apiBaseUrl });
  mkdirSync(directory, { recursive: true });
  if (existsSync(path)) {
    const existing = readFileSync(path, "utf8");
    if (!existing.includes(CODEX_MARKER)) {
      throw new Fault(409, "codex_profile_conflict", `Codex profile already exists: ${path}. Rename it or remove it before connecting webgpt-api.`);
    }
    if (existing === content) return { profile: CODEX_PROFILE, path, changed: false };
  }
  writeFileSync(path, content, { encoding: "utf8", mode: 0o600 });
  return { profile: CODEX_PROFILE, path, changed: true };
}

export function clientEnvironment(key, env = process.env, apiBaseUrl = API_BASE_URL) {
  return {
    ...env,
    WEBGPT_API_URL: apiBaseUrl,
    WEBGPT_API_KEY: key,
    OPENAI_BASE_URL: apiBaseUrl,
    OPENAI_API_BASE: apiBaseUrl,
    OPENAI_API_KEY: key,
    OPENAI_MODEL: "auto",
  };
}

function isCodexCommand(command) {
  const name = basename(command).toLowerCase().replace(/\.(cmd|exe|bat)$/i, "");
  return name === "codex";
}

function hasProfileArgument(args) {
  return args.some((argument, index) => argument === "--profile" || argument.startsWith("--profile=") || (index > 0 && args[index - 1] === "--profile"));
}

export async function runClient(args, { env = process.env, directory = dataDirectory(), cwd = process.cwd(), apiBaseUrl = API_BASE_URL, nodePath = process.execPath, projectRoot = resolve(import.meta.dirname, "..") } = {}) {
  if (!Array.isArray(args) || !args.length || !args[0]) throw new Fault(400, "missing_client", "Use run -- <tool> [arguments], or double-click webgpt.cmd to open a ready terminal.");
  const key = initialize(directory).key;
  const command = args[0];
  let childArgs = args.slice(1);
  if (isCodexCommand(command)) {
    installCodexProfile({ env, nodePath, projectRoot, apiBaseUrl });
    if (!hasProfileArgument(childArgs)) childArgs = ["--profile", CODEX_PROFILE, ...childArgs];
  }
  return new Promise((resolvePromise, reject) => {
    const child = spawn(command, childArgs, {
      cwd,
      env: clientEnvironment(key, env, apiBaseUrl),
      stdio: "inherit",
      windowsHide: false,
    });
    child.once("error", error => {
      if (error.code === "ENOENT") reject(new Fault(127, "client_not_found", `Could not find client: ${command}`));
      else reject(error);
    });
    child.once("exit", (code, signal) => resolvePromise(code ?? (signal ? 1 : 0)));
  });
}

export async function openClientShell({ env = process.env, directory = dataDirectory(), cwd = process.cwd(), apiBaseUrl = API_BASE_URL } = {}) {
  const key = initialize(directory).key;
  const shell = platform() === "win32" ? (env.ComSpec || "cmd.exe") : (env.SHELL || "/bin/sh");
  const args = platform() === "win32" ? ["/K", "title webgpt-api - ready terminal"] : ["-i"];
  return new Promise((resolvePromise, reject) => {
    const child = spawn(shell, args, { cwd, env: clientEnvironment(key, env, apiBaseUrl), stdio: "inherit", windowsHide: false });
    child.once("error", reject);
    child.once("exit", code => resolvePromise(code ?? 0));
  });
}
